/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Leandro
 */
public class JanelaCadastrarEst extends javax.swing.JFrame {

    /**
     * Creates new form JanelaCadastrarEst
     */
    public JanelaCadastrarEst() {
        initComponents();
        setIcon();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MarcaPanda = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Nome = new javax.swing.JLabel();
        CNPJ = new javax.swing.JLabel();
        Endereco = new javax.swing.JLabel();
        Telefone = new javax.swing.JLabel();
        NomeLoja = new javax.swing.JTextField();
        EnderecoLoja = new javax.swing.JTextField();
        CNPJLoja = new javax.swing.JFormattedTextField();
        TelLoja = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        BotaoCadastrarLoja = new javax.swing.JButton();
        BotaoApagarCamposLoja = new javax.swing.JButton();
        BotaoCancelarLoja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MarcaPanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visaoTeste/panda_bg.png"))); // NOI18N
        getContentPane().add(MarcaPanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 302, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Nome.setText("Nome:");

        CNPJ.setText("CNPJ:");

        Endereco.setText("Endereço:");

        Telefone.setText("Telefone:");

        NomeLoja.setToolTipText("Nome do Estabelecimento");

        EnderecoLoja.setToolTipText("Endereço do estabelecimento");

        CNPJLoja.setToolTipText("CNPJ do estabelecimento");
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##.###.###/####-##");  
            CNPJLoja = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }

        TelLoja.setToolTipText("Telefone do estabelecimento");
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("(##)####-####");  
            TelLoja = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CNPJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CNPJLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Telefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TelLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Endereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EnderecoLoja))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NomeLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome)
                    .addComponent(NomeLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CNPJLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Endereco)
                    .addComponent(EnderecoLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefone)
                    .addComponent(TelLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 690, 170));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Cadastrar Loja");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        BotaoCadastrarLoja.setText("Confirmar");
        BotaoCadastrarLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarLojaActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoCadastrarLoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        BotaoApagarCamposLoja.setText("Limpar");
        BotaoApagarCamposLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoApagarCamposLojaActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoApagarCamposLoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 80, -1));

        BotaoCancelarLoja.setText("Cancelar");
        BotaoCancelarLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarLojaActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoCancelarLoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoApagarCamposLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoApagarCamposLojaActionPerformed
        // TODO add your handling code here:
        NomeLoja.setText("");
        CNPJLoja.setText("");
        EnderecoLoja.setText("");
        TelLoja.setText("");
    }//GEN-LAST:event_BotaoApagarCamposLojaActionPerformed

    private void BotaoCancelarLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarLojaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JanelaInicialiCards frame = new JanelaInicialiCards();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_BotaoCancelarLojaActionPerformed

    private void BotaoCadastrarLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarLojaActionPerformed
        // TODO add your handling code here:
         NomeLoja.getText();
         CNPJLoja.getText();
         EnderecoLoja.getText();
         TelLoja.getText();
        
            if ((NomeLoja.getText().length()>0)
                &&(CNPJLoja.getText().length()>0)
                    &&(EnderecoLoja.getText().length()>0)
                        &&(TelLoja.getText().length()>0)){
                JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso.");
                this.dispose();
                JanelaInicialiCards frame = new JanelaInicialiCards();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);   
            }else{
                JOptionPane.showMessageDialog(null, "Existe algum campo em branco..");
            }
    }//GEN-LAST:event_BotaoCadastrarLojaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCadastrarEst().setVisible(true);          
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoApagarCamposLoja;
    private javax.swing.JButton BotaoCadastrarLoja;
    private javax.swing.JButton BotaoCancelarLoja;
    private javax.swing.JLabel CNPJ;
    private javax.swing.JFormattedTextField CNPJLoja;
    private javax.swing.JLabel Endereco;
    private javax.swing.JTextField EnderecoLoja;
    private javax.swing.JLabel MarcaPanda;
    private javax.swing.JLabel Nome;
    private javax.swing.JTextField NomeLoja;
    private javax.swing.JFormattedTextField TelLoja;
    private javax.swing.JLabel Telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("favicon.png")));
    }
}

