/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import visao.JanelaCadastrarUsuario;
import visao.JanelaCadastrarEst;
import java.awt.Toolkit;

/**
 *
 * @author Uguinho
 */
public class JanelaInicialiCards extends javax.swing.JFrame {

    /**
     * Creates new form JanelaAdmin
     */
    public JanelaInicialiCards() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MenuInicial = new javax.swing.JMenuBar();
        Usuário = new javax.swing.JMenu();
        IrJanelaUsuario = new javax.swing.JMenuItem();
        Administrador = new javax.swing.JMenu();
        MenuUsuario = new javax.swing.JMenu();
        NovoUsuario = new javax.swing.JMenuItem();
        EditarUsuario = new javax.swing.JMenuItem();
        ExcluirUsuario = new javax.swing.JMenuItem();
        MenuEstabelecimento = new javax.swing.JMenu();
        NovoEstabelecimento = new javax.swing.JMenuItem();
        EditarEstabelecimento = new javax.swing.JMenuItem();
        ExcluirEstabelecimento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("iCards - iAdmin");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 48)); // NOI18N
        jLabel1.setText("Bem-Vindo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 610, 140));

        jLabel2.setFont(new java.awt.Font("Cooper Black", 1, 48)); // NOI18N
        jLabel2.setText("ao iCards!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 280, 150));

        Usuário.setText("Usuário");
        Usuário.setToolTipText("Acessar sua conta");

        IrJanelaUsuario.setText("Início");
        IrJanelaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrJanelaUsuarioActionPerformed(evt);
            }
        });
        Usuário.add(IrJanelaUsuario);

        MenuInicial.add(Usuário);

        Administrador.setText("Administrador");

        MenuUsuario.setText("Usuário");

        NovoUsuario.setText("Novo");
        NovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoUsuarioActionPerformed(evt);
            }
        });
        MenuUsuario.add(NovoUsuario);

        EditarUsuario.setText("Editar");
        EditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarUsuarioActionPerformed(evt);
            }
        });
        MenuUsuario.add(EditarUsuario);

        ExcluirUsuario.setText("Excluir");
        ExcluirUsuario.setToolTipText("Excluir usuário");
        ExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirUsuarioActionPerformed(evt);
            }
        });
        MenuUsuario.add(ExcluirUsuario);

        Administrador.add(MenuUsuario);

        MenuEstabelecimento.setText("Estabelecimento");
        MenuEstabelecimento.setToolTipText("Cadastra novo usuário");

        NovoEstabelecimento.setText("Novo");
        NovoEstabelecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoEstabelecimentoActionPerformed(evt);
            }
        });
        MenuEstabelecimento.add(NovoEstabelecimento);

        EditarEstabelecimento.setText("Editar");
        EditarEstabelecimento.setToolTipText("Editar informações de usuário");
        EditarEstabelecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarEstabelecimentoActionPerformed(evt);
            }
        });
        MenuEstabelecimento.add(EditarEstabelecimento);

        ExcluirEstabelecimento.setText("Excluir");
        ExcluirEstabelecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirEstabelecimentoActionPerformed(evt);
            }
        });
        MenuEstabelecimento.add(ExcluirEstabelecimento);

        Administrador.add(MenuEstabelecimento);

        MenuInicial.add(Administrador);

        setJMenuBar(MenuInicial);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-728)/2, (screenSize.height-514)/2, 728, 514);
    }// </editor-fold>//GEN-END:initComponents

    private void NovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoUsuarioActionPerformed
        // TODO add your handling code here:
        JanelaCadastrarUsuario frame = new JanelaCadastrarUsuario();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NovoUsuarioActionPerformed

    private void EditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarUsuarioActionPerformed
        // TODO add your handling code here:
        JanelaCadastrarUsuario frame = new JanelaCadastrarUsuario();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EditarUsuarioActionPerformed

    private void ExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExcluirUsuarioActionPerformed

    private void NovoEstabelecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoEstabelecimentoActionPerformed
        // TODO add your handling code here:
        JanelaCadastrarEst frame = new JanelaCadastrarEst();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NovoEstabelecimentoActionPerformed

    private void EditarEstabelecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarEstabelecimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarEstabelecimentoActionPerformed

    private void ExcluirEstabelecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirEstabelecimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExcluirEstabelecimentoActionPerformed

    private void IrJanelaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrJanelaUsuarioActionPerformed
        // TODO add your handling code here:
        JanelaInicioUsuario frame = new JanelaInicioUsuario();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IrJanelaUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaInicialiCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaInicialiCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaInicialiCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaInicialiCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaInicialiCards().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Administrador;
    private javax.swing.JMenuItem EditarEstabelecimento;
    private javax.swing.JMenuItem EditarUsuario;
    private javax.swing.JMenuItem ExcluirEstabelecimento;
    private javax.swing.JMenuItem ExcluirUsuario;
    private javax.swing.JMenuItem IrJanelaUsuario;
    private javax.swing.JMenu MenuEstabelecimento;
    private javax.swing.JMenuBar MenuInicial;
    private javax.swing.JMenu MenuUsuario;
    private javax.swing.JMenuItem NovoEstabelecimento;
    private javax.swing.JMenuItem NovoUsuario;
    private javax.swing.JMenu Usuário;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
