/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Leandro
 */
public class JanelaAlterarSenha extends javax.swing.JFrame {

    /**
     * Creates new form JanelaAlterarSenha
     */
    public JanelaAlterarSenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AlterarSenha = new javax.swing.JLabel();
        SenhaAtualLabel = new javax.swing.JLabel();
        SenhaAtual = new javax.swing.JPasswordField();
        NovaSenhaLabel = new javax.swing.JLabel();
        NovaSenha = new javax.swing.JPasswordField();
        ConfirmarAlterarSenha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alterar Senha");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AlterarSenha.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        AlterarSenha.setText("Alterar Senha");
        getContentPane().add(AlterarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 47, -1, -1));

        SenhaAtualLabel.setText("Digite sua senha atual:");
        getContentPane().add(SenhaAtualLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 132, -1, -1));
        getContentPane().add(SenhaAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 129, 130, -1));

        NovaSenhaLabel.setText("Digite sua nova senha:");
        getContentPane().add(NovaSenhaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 184, -1, -1));
        getContentPane().add(NovaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 181, 130, -1));

        ConfirmarAlterarSenha.setText("Confirmar");
        ConfirmarAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarAlterarSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmarAlterarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 263, -1, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-728)/2, (screenSize.height-514)/2, 728, 514);
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmarAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarAlterarSenhaActionPerformed
        // TODO add your handling code here:
        String velhasenha = SenhaAtual.getText();
        String novasenha = NovaSenha.getText();
        if ((velhasenha.length()>0)&&(novasenha.length()>0)){
             JOptionPane.showMessageDialog(null, "Senha alterada com sucesso.");
             this.dispose();
            JanelaUsuario frame = new JanelaUsuario();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
            
             
        }else{
            JOptionPane.showMessageDialog(null, "Existe campo em branco.");
        }
        
    }//GEN-LAST:event_ConfirmarAlterarSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaAlterarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaAlterarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaAlterarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaAlterarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JanelaAlterarSenha().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlterarSenha;
    private javax.swing.JButton ConfirmarAlterarSenha;
    private javax.swing.JPasswordField NovaSenha;
    private javax.swing.JLabel NovaSenhaLabel;
    private javax.swing.JPasswordField SenhaAtual;
    private javax.swing.JLabel SenhaAtualLabel;
    // End of variables declaration//GEN-END:variables

}
