/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Leandro
 */
public class JanelaCadastrarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form JanelaCadastrarUsuario
     */
    public JanelaCadastrarUsuario() {
        initComponents();
        CPFDependente.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoTipoUsuario = new javax.swing.ButtonGroup();
        GrupoSexo = new javax.swing.ButtonGroup();
        PainelCadastroUsuario = new javax.swing.JPanel();
        PainelPessoal = new javax.swing.JPanel();
        Nome = new javax.swing.JLabel();
        NomeUsuario = new javax.swing.JTextField();
        CPF = new javax.swing.JLabel();
        CPFUsuario = new javax.swing.JFormattedTextField();
        DataNasc = new javax.swing.JLabel();
        DataNascUsuario = new javax.swing.JFormattedTextField();
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/####");  
            DataNascUsuario = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }
        Nacionalidade = new javax.swing.JLabel();
        NacionalidadeUsuario = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        erroNome = new javax.swing.JLabel();
        CPFErro = new javax.swing.JLabel();
        ErroEmail = new javax.swing.JLabel();
        erroNasc = new javax.swing.JLabel();
        ErroNac = new javax.swing.JLabel();
        PainelEndereco = new javax.swing.JPanel();
        Endereco = new javax.swing.JLabel();
        EnderecoUsuario = new javax.swing.JTextField();
        Telefone = new javax.swing.JLabel();
        TelUsuario = new javax.swing.JFormattedTextField();
        erroEnd = new javax.swing.JLabel();
        erroTel = new javax.swing.JLabel();
        PainelTipo = new javax.swing.JPanel();
        Dependente = new javax.swing.JRadioButton();
        Titular = new javax.swing.JRadioButton();
        TipodeUsuario = new javax.swing.JLabel();
        CPFdoDependente = new javax.swing.JLabel();
        CPFDependente = new javax.swing.JFormattedTextField();
        todosCampos = new javax.swing.JLabel();
        ErroTipoUsuario = new javax.swing.JLabel();
        erroCpfTit = new javax.swing.JLabel();
        CancelarCadastroUsuario = new javax.swing.JButton();
        LimparCadastroUsuario = new javax.swing.JButton();
        CadastrarUsuario = new javax.swing.JButton();
        iCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Usuário");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelPessoal.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações Pessoais"));

        Nome.setText("Nome:");

        NomeUsuario.setToolTipText("Nome");

        CPF.setText("CPF:");

        CPFUsuario.setToolTipText("CPF do Usuário");
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("###.###.###-##");  
            CPFUsuario = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }

        DataNasc.setText("Data de Nascimento:");

        DataNascUsuario.setToolTipText("Data de Nascimento");

        Nacionalidade.setText("Nacionalidade:");

        NacionalidadeUsuario.setToolTipText("Nacionalidade");

        EmailLabel.setText("Email:");

        CPFErro.setForeground(new java.awt.Color(255, 0, 0));

        ErroEmail.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout PainelPessoalLayout = new javax.swing.GroupLayout(PainelPessoal);
        PainelPessoal.setLayout(PainelPessoalLayout);
        PainelPessoalLayout.setHorizontalGroup(
            PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPessoalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPessoalLayout.createSequentialGroup()
                        .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelPessoalLayout.createSequentialGroup()
                                .addComponent(Nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(erroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelPessoalLayout.createSequentialGroup()
                                .addComponent(CPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ErroEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CPFErro, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CPFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelPessoalLayout.createSequentialGroup()
                        .addComponent(EmailLabel)
                        .addGap(18, 18, 18)
                        .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DataNasc)
                            .addGroup(PainelPessoalLayout.createSequentialGroup()
                                .addComponent(Nacionalidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ErroNac, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelPessoalLayout.createSequentialGroup()
                                .addComponent(erroNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DataNascUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NacionalidadeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        PainelPessoalLayout.setVerticalGroup(
            PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPessoalLayout.createSequentialGroup()
                .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PainelPessoalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nome)
                            .addComponent(NomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(erroNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPessoalLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DataNasc)
                            .addComponent(DataNascUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(erroNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CPF)
                        .addComponent(CPFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CPFErro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmailLabel)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nacionalidade)
                            .addComponent(NacionalidadeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(ErroEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ErroNac, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        PainelEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações de Endereço"));

        Endereco.setText("Endereço:");

        EnderecoUsuario.setToolTipText("Digite Endereço");

        Telefone.setText("Telefone:");

        TelUsuario.setToolTipText("Telefone");
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("(##)####-####");  
            TelUsuario = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }

        javax.swing.GroupLayout PainelEnderecoLayout = new javax.swing.GroupLayout(PainelEndereco);
        PainelEndereco.setLayout(PainelEnderecoLayout);
        PainelEnderecoLayout.setHorizontalGroup(
            PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelEnderecoLayout.createSequentialGroup()
                        .addComponent(Endereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(erroEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelEnderecoLayout.createSequentialGroup()
                        .addComponent(Telefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(erroTel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelEnderecoLayout.createSequentialGroup()
                        .addComponent(EnderecoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(107, Short.MAX_VALUE))
                    .addGroup(PainelEnderecoLayout.createSequentialGroup()
                        .addComponent(TelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PainelEnderecoLayout.setVerticalGroup(
            PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Endereco)
                        .addComponent(EnderecoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(erroEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Telefone)
                        .addComponent(TelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(erroTel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelTipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações de Tipo"));
        PainelTipo.setPreferredSize(new java.awt.Dimension(740, 203));

        GrupoTipoUsuario.add(Dependente);
        Dependente.setText("Dependente");
        Dependente.setActionCommand("DEPENDENTE");
        Dependente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DependenteActionPerformed(evt);
            }
        });

        GrupoTipoUsuario.add(Titular);
        Titular.setText("Titular");
        Titular.setToolTipText("");
        Titular.setActionCommand("TITULAR");
        Titular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitularActionPerformed(evt);
            }
        });

        TipodeUsuario.setText("Tipo de Usuário:");

        CPFdoDependente.setText("CPF Dependente:");

        CPFDependente.setEditable(false);
        CPFDependente.setToolTipText("CPF do Dependente");
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("###.###.###-##");  
            CPFDependente = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }

        todosCampos.setForeground(new java.awt.Color(255, 0, 0));

        ErroTipoUsuario.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout PainelTipoLayout = new javax.swing.GroupLayout(PainelTipo);
        PainelTipo.setLayout(PainelTipoLayout);
        PainelTipoLayout.setHorizontalGroup(
            PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TipodeUsuario)
                    .addComponent(CPFdoDependente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ErroTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(erroCpfTit, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelTipoLayout.createSequentialGroup()
                        .addGroup(PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelTipoLayout.createSequentialGroup()
                                .addComponent(Titular)
                                .addGap(126, 126, 126)
                                .addComponent(todosCampos, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                            .addGroup(PainelTipoLayout.createSequentialGroup()
                                .addComponent(Dependente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(166, 166, 166))
                    .addGroup(PainelTipoLayout.createSequentialGroup()
                        .addComponent(CPFDependente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 446, Short.MAX_VALUE))))
        );
        PainelTipoLayout.setVerticalGroup(
            PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelTipoLayout.createSequentialGroup()
                        .addComponent(todosCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PainelTipoLayout.createSequentialGroup()
                        .addGroup(PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Dependente)
                                .addComponent(TipodeUsuario))
                            .addComponent(ErroTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelTipoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Titular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CPFdoDependente)
                                    .addComponent(CPFDependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelTipoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(erroCpfTit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))))))
        );

        CancelarCadastroUsuario.setText("Cancelar");
        CancelarCadastroUsuario.setToolTipText("Cancelar Operação");
        CancelarCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarCadastroUsuarioActionPerformed(evt);
            }
        });

        LimparCadastroUsuario.setText("Limpar");
        LimparCadastroUsuario.setToolTipText("Limpar Campos");
        LimparCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparCadastroUsuarioActionPerformed(evt);
            }
        });

        CadastrarUsuario.setText("Cadastrar");
        CadastrarUsuario.setToolTipText("Cadastrar Usuário");
        CadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelCadastroUsuarioLayout = new javax.swing.GroupLayout(PainelCadastroUsuario);
        PainelCadastroUsuario.setLayout(PainelCadastroUsuarioLayout);
        PainelCadastroUsuarioLayout.setHorizontalGroup(
            PainelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroUsuarioLayout.createSequentialGroup()
                .addGroup(PainelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCadastroUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PainelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PainelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PainelPessoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PainelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelCadastroUsuarioLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(CadastrarUsuario)
                        .addGap(89, 89, 89)
                        .addComponent(LimparCadastroUsuario)
                        .addGap(73, 73, 73)
                        .addComponent(CancelarCadastroUsuario)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        PainelCadastroUsuarioLayout.setVerticalGroup(
            PainelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroUsuarioLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(PainelPessoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PainelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(PainelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelarCadastroUsuario)
                    .addComponent(LimparCadastroUsuario)
                    .addComponent(CadastrarUsuario))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        getContentPane().add(PainelCadastroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 610));

        iCadastro.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        iCadastro.setText("iCadastro");
        getContentPane().add(iCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        setSize(new java.awt.Dimension(728, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarCadastroUsuarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JanelaInicialiCards frame = new JanelaInicialiCards();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_CancelarCadastroUsuarioActionPerformed

    private void LimparCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparCadastroUsuarioActionPerformed
        // TODO add your handling code here:
        NomeUsuario.setText("");
        CPFUsuario.setText("");
        DataNascUsuario.setText("");
        NacionalidadeUsuario.setText("");
        Email.setText("");
        EnderecoUsuario.setText("");
        TelUsuario.setText("");
        CPFDependente.setText("");
        GrupoTipoUsuario.clearSelection();   
    }//GEN-LAST:event_LimparCadastroUsuarioActionPerformed

    private void CadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarUsuarioActionPerformed
        // TODO add your handling code here:
        String nomeUsuario = NomeUsuario.getText();
        String cpfUsuario1 = CPFUsuario.getText().replaceAll("[.]","");
        String cpfUsuario = cpfUsuario1.replaceAll("-","");
        
        String dataNasc = DataNascUsuario.getText().replaceAll("/", "");
        String nacionalidadeUsuario = NacionalidadeUsuario.getText();
        String email = Email.getText();
        String enderecoUsuario = EnderecoUsuario.getText();
        String telUsuario1 = TelUsuario.getText().replaceAll("-", "");
        String telUsuario2 = telUsuario1.replaceAll("[(]", "");
        String telUsuario = telUsuario2.replaceAll("[)]", "");
        
        String tipoUsuario = GrupoTipoUsuario.getSelection().getActionCommand();
      
        if((nomeUsuario.isEmpty())||(cpfUsuario.isEmpty())||(email.isEmpty())||(dataNasc.isEmpty())
                ||(enderecoUsuario.isEmpty())||(nacionalidadeUsuario.isEmpty())
                ||(telUsuario.isEmpty())||(tipoUsuario.isEmpty())){
            todosCampos.setText( "* Todos os campos devem ser preenchidos");
        
        if (nomeUsuario.isEmpty()){
                erroNome.setText("*");
        }
        else if (cpfUsuario1.isEmpty()){
                CPFErro.setText("*");
        }
        else if (email.isEmpty()){
                ErroEmail.setText("*");
        }
        else if (enderecoUsuario.isEmpty()){
                erroEnd.setText("*");
        }
        else if (dataNasc.isEmpty()){
                erroNasc.setText("*");
        }
        else if (nacionalidadeUsuario.isEmpty()){
                ErroNac.setText("*");
        }
        else if (telUsuario.isEmpty()){
                erroTel.setText("*");
        }
        else if (tipoUsuario.isEmpty()){
                ErroTipoUsuario.setText("*");
        }
        }   
        else{
            todosCampos.setText("PARABENS");
            //this.dispose();
           // JanelaInicialiCards frame = new JanelaInicialiCards();
          //  frame.setLocationRelativeTo(null);
          //  frame.setVisible(true);
        }
        if (tipoUsuario =="TITULAR"){
            String cpfDependente = null;
        }
        else{
            String cpfDependente1 = CPFDependente.getText().replaceAll("[.]","");
            String cpfDependente = cpfDependente1.replaceAll("-","");  
        }
        
    }//GEN-LAST:event_CadastrarUsuarioActionPerformed

    private void DependenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DependenteActionPerformed
        // TODO add your handling code here:
        CPFDependente.setEditable(true);
    }//GEN-LAST:event_DependenteActionPerformed

    private void TitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitularActionPerformed
        // TODO add your handling code here:
        CPFDependente.setEditable(false);
        
    }//GEN-LAST:event_TitularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCadastrarUsuario().setVisible(true);
            }
              
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPF;
    private javax.swing.JFormattedTextField CPFDependente;
    private javax.swing.JLabel CPFErro;
    private javax.swing.JFormattedTextField CPFUsuario;
    private javax.swing.JLabel CPFdoDependente;
    private javax.swing.JButton CadastrarUsuario;
    private javax.swing.JButton CancelarCadastroUsuario;
    private javax.swing.JLabel DataNasc;
    private javax.swing.JFormattedTextField DataNascUsuario;
    private javax.swing.JRadioButton Dependente;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel Endereco;
    private javax.swing.JTextField EnderecoUsuario;
    private javax.swing.JLabel ErroEmail;
    private javax.swing.JLabel ErroNac;
    private javax.swing.JLabel ErroTipoUsuario;
    private javax.swing.ButtonGroup GrupoSexo;
    private javax.swing.ButtonGroup GrupoTipoUsuario;
    private javax.swing.JButton LimparCadastroUsuario;
    private javax.swing.JLabel Nacionalidade;
    private javax.swing.JTextField NacionalidadeUsuario;
    private javax.swing.JLabel Nome;
    private javax.swing.JTextField NomeUsuario;
    private javax.swing.JPanel PainelCadastroUsuario;
    private javax.swing.JPanel PainelEndereco;
    private javax.swing.JPanel PainelPessoal;
    private javax.swing.JPanel PainelTipo;
    private javax.swing.JFormattedTextField TelUsuario;
    private javax.swing.JLabel Telefone;
    private javax.swing.JLabel TipodeUsuario;
    private javax.swing.JRadioButton Titular;
    private javax.swing.JLabel erroCpfTit;
    private javax.swing.JLabel erroEnd;
    private javax.swing.JLabel erroNasc;
    private javax.swing.JLabel erroNome;
    private javax.swing.JLabel erroTel;
    private javax.swing.JLabel iCadastro;
    private javax.swing.JLabel todosCampos;
    // End of variables declaration//GEN-END:variables

}
