/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.logging.Level;
import java.util.logging.Logger;
import negocio.GerenciarDB;

/**
 *
 * @author Leandro
 */
public class JanelaDeletarEst extends javax.swing.JFrame {

    /**
     * Creates new form DeletarEstabelecimento
     */
    public JanelaDeletarEst() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConfirmarDelLoja = new javax.swing.JButton();
        CancelarDelLoja = new javax.swing.JButton();
        DelCNPJ = new javax.swing.JLabel();
        DeletarEstabelecimento = new javax.swing.JLabel();
        deletarLoja = new javax.swing.JFormattedTextField();
        todosCampos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Deletar Estabelecimento");
        setMinimumSize(new java.awt.Dimension(670, 450));

        ConfirmarDelLoja.setText("Confirmar");
        ConfirmarDelLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarDelLojaActionPerformed(evt);
            }
        });

        CancelarDelLoja.setText("Cancelar");
        CancelarDelLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarDelLojaActionPerformed(evt);
            }
        });

        DelCNPJ.setText("Digite o CNPJ do Estabelecimento:");

        DeletarEstabelecimento.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        DeletarEstabelecimento.setText("Deletar Estabelecimento");

        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##.###.###/####-##");  
            deletarLoja = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }
        deletarLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarLojaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 177, Short.MAX_VALUE)
                .addComponent(DeletarEstabelecimento)
                .addGap(156, 156, 156))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(ConfirmarDelLoja)
                        .addGap(195, 195, 195)
                        .addComponent(CancelarDelLoja))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(DelCNPJ)
                        .addGap(18, 18, 18)
                        .addComponent(deletarLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(todosCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(DeletarEstabelecimento)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DelCNPJ)
                    .addComponent(deletarLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(todosCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmarDelLoja)
                    .addComponent(CancelarDelLoja))
                .addGap(97, 97, 97))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmarDelLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarDelLojaActionPerformed
        // TODO add your handling code here:
        String CNPJ = deletarLoja.getText().replaceAll("[.]","");
        CNPJ = CNPJ.replaceAll("[/]","");
        CNPJ = CNPJ.replaceAll("[-]","");
        
        if ((CNPJ.isEmpty()) || ("        ".equals(CNPJ)) ) {
            todosCampos.setText("O campo deve ser preenchido");
        } else {
            try {
                 GerenciarDB banco = new GerenciarDB();
                 
                 if (banco.checkEstabelecimentoDB(CNPJ)) {
                    banco.delEstabelecimento(CNPJ);
                    JanelaInicioAdmin frame = new JanelaInicioAdmin();
                    frame.setLocationRelativeTo(null);
                    frame.setVisible(true);
                    this.dispose();
                 } else {
                     System.out.println("NAO EXISTE ESSE CARTAO ERRO");
                 }
            } catch (Exception ex) {
                Logger.getLogger(JanelaDeletarCartao.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
    }//GEN-LAST:event_ConfirmarDelLojaActionPerformed

    private void CancelarDelLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarDelLojaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JanelaInicioAdmin frame = new JanelaInicioAdmin();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_CancelarDelLojaActionPerformed

    private void deletarLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarLojaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletarLojaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaDeletarEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaDeletarEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaDeletarEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaDeletarEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaDeletarEst().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarDelLoja;
    private javax.swing.JButton ConfirmarDelLoja;
    private javax.swing.JLabel DelCNPJ;
    private javax.swing.JLabel DeletarEstabelecimento;
    private javax.swing.JFormattedTextField deletarLoja;
    private javax.swing.JLabel todosCampos;
    // End of variables declaration//GEN-END:variables
}
