/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Leandro
 */
public class JanelaCadastrarEst extends javax.swing.JFrame {

    /**
     * Creates new form JanelaCadastrarEst
     */
    public JanelaCadastrarEst() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Nome = new javax.swing.JLabel();
        NomeLoja = new javax.swing.JTextField();
        CNPJ = new javax.swing.JLabel();
        CNPJLoja = new javax.swing.JFormattedTextField();
        Endereco = new javax.swing.JLabel();
        EnderecoLoja = new javax.swing.JTextField();
        Telefone = new javax.swing.JLabel();
        TelLoja = new javax.swing.JFormattedTextField();
        todosCampos = new javax.swing.JLabel();
        infoErro = new javax.swing.JLabel();
        BotaoCadastrarLoja = new javax.swing.JButton();
        BotaoApagarCamposLoja = new javax.swing.JButton();
        BotaoCancelarLoja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Cadastrar Loja");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Nome.setText("Nome:");

        NomeLoja.setToolTipText("Nome do Estabelecimento");

        CNPJ.setText("CNPJ:");

        CNPJLoja.setToolTipText("CNPJ do estabelecimento");
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##.###.###/####-##");  
            CNPJLoja = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }

        Endereco.setText("Endereço:");

        EnderecoLoja.setToolTipText("Endereço do estabelecimento");

        Telefone.setText("Telefone:");

        TelLoja.setToolTipText("Telefone do estabelecimento");
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("(##)####-####");  
            TelLoja = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(infoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Nome)
                                    .addComponent(CNPJ))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Telefone)
                                    .addComponent(Endereco))
                                .addGap(15, 15, 15)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(todosCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CNPJLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EnderecoLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NomeLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TelLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(todosCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome)
                    .addComponent(NomeLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CNPJLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Endereco)
                    .addComponent(EnderecoLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(infoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefone)
                    .addComponent(TelLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 690, 200));

        BotaoCadastrarLoja.setText("Confirmar");
        BotaoCadastrarLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarLojaActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoCadastrarLoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        BotaoApagarCamposLoja.setText("Limpar");
        BotaoApagarCamposLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoApagarCamposLojaActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoApagarCamposLoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 80, -1));

        BotaoCancelarLoja.setText("Cancelar");
        BotaoCancelarLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarLojaActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoCancelarLoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 80, -1));

        setSize(new java.awt.Dimension(728, 514));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoApagarCamposLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoApagarCamposLojaActionPerformed
        // TODO add your handling code here:
        NomeLoja.setText("");
        CNPJLoja.setText("");
        EnderecoLoja.setText("");
        TelLoja.setText("");
    }//GEN-LAST:event_BotaoApagarCamposLojaActionPerformed

    private void BotaoCancelarLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarLojaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JanelaInicialiCards frame = new JanelaInicialiCards();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_BotaoCancelarLojaActionPerformed

    private void BotaoCadastrarLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarLojaActionPerformed
        // TODO add your handling code here:
         NomeLoja.getText();
         CNPJLoja.getText();
         EnderecoLoja.getText();
         TelLoja.getText();
        
            if ((NomeLoja.getText().isEmpty())&&(EnderecoLoja.getText().isEmpty())&&(TelLoja.getText().isEmpty())){
                
                todosCampos.setText("Você deve preencher todos os campos.");
                   
            }
            else if(NomeLoja.getText().isEmpty()){
                infoErro.setText("Nome é um campo necessário.");
            }
            
            else{
                this.dispose();
                JanelaInicialiCards frame = new JanelaInicialiCards();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true); 
            }
    }//GEN-LAST:event_BotaoCadastrarLojaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCadastrarEst().setVisible(true);          
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoApagarCamposLoja;
    private javax.swing.JButton BotaoCadastrarLoja;
    private javax.swing.JButton BotaoCancelarLoja;
    private javax.swing.JLabel CNPJ;
    private javax.swing.JFormattedTextField CNPJLoja;
    private javax.swing.JLabel Endereco;
    private javax.swing.JTextField EnderecoLoja;
    private javax.swing.JLabel Nome;
    private javax.swing.JTextField NomeLoja;
    private javax.swing.JFormattedTextField TelLoja;
    private javax.swing.JLabel Telefone;
    private javax.swing.JLabel infoErro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel todosCampos;
    // End of variables declaration//GEN-END:variables

}

