/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;


import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Leandro
 */
public class JanelaCadastrarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form JanelaCadastrarUsuario
     */
    public JanelaCadastrarUsuario() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoTipoUsuario = new javax.swing.ButtonGroup();
        GrupoSexo = new javax.swing.ButtonGroup();
        BarraRolagemCadastroUsuario = new javax.swing.JScrollPane();
        PainelCadastroUsuario = new javax.swing.JPanel();
        PainelPessoal = new javax.swing.JPanel();
        CPF = new javax.swing.JLabel();
        DataNasc = new javax.swing.JLabel();
        Sexo = new javax.swing.JLabel();
        NomeUsuario = new javax.swing.JTextField();
        Nome = new javax.swing.JLabel();
        DataNascUsuario = new javax.swing.JFormattedTextField();
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/####");  
            DataNascUsuario = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }
        Nacionalidade = new javax.swing.JLabel();
        NacionalidadeUsuario = new javax.swing.JTextField();
        UsuarioFeminino = new javax.swing.JRadioButton();
        UsuarioMasculino = new javax.swing.JRadioButton();
        CPFUsuario = new javax.swing.JFormattedTextField();
        PainelEndereco = new javax.swing.JPanel();
        Endereco = new javax.swing.JLabel();
        Bairro = new javax.swing.JLabel();
        Cidade = new javax.swing.JLabel();
        UF = new javax.swing.JLabel();
        UFUsuario = new javax.swing.JTextField();
        CidadeUsuario = new javax.swing.JTextField();
        BairroUsuario = new javax.swing.JTextField();
        EnderecoUsuario = new javax.swing.JTextField();
        Telefone = new javax.swing.JLabel();
        TelUsuario = new javax.swing.JFormattedTextField();
        PainelTipo = new javax.swing.JPanel();
        Dependente = new javax.swing.JRadioButton();
        Titular = new javax.swing.JRadioButton();
        TipodeUsuario = new javax.swing.JLabel();
        CPFdoDependente = new javax.swing.JLabel();
        CPFDependente = new javax.swing.JFormattedTextField();
        Senha = new javax.swing.JLabel();
        SenhaUsuario = new javax.swing.JPasswordField();
        MarcaPanda = new javax.swing.JLabel();
        CancelarCadastroUsuario = new javax.swing.JButton();
        LimparCadastroUsuario = new javax.swing.JButton();
        CadastrarUsuario = new javax.swing.JButton();
        iCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Usuário");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraRolagemCadastroUsuario.setWheelScrollingEnabled(false);

        PainelPessoal.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações Pessoais"));

        CPF.setText("CPF:");

        DataNasc.setText("Data de Nascimento:");

        Sexo.setText("Sexo:");

        NomeUsuario.setToolTipText("Nome");

        Nome.setText("Nome:");

        DataNascUsuario.setToolTipText("Data de Nascimento");

        Nacionalidade.setText("Nacionalidade:");

        NacionalidadeUsuario.setToolTipText("Nacionalidade");

        GrupoSexo.add(UsuarioFeminino);
        UsuarioFeminino.setText("Feminino");
        UsuarioFeminino.setToolTipText("Selecione Feminino");

        GrupoSexo.add(UsuarioMasculino);
        UsuarioMasculino.setText("Masculino");
        UsuarioMasculino.setToolTipText("Selecione Masculino");

        CPFUsuario.setToolTipText("CPF do Usuário");
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("###.###.###-##");  
            CPFUsuario = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }

        javax.swing.GroupLayout PainelPessoalLayout = new javax.swing.GroupLayout(PainelPessoal);
        PainelPessoal.setLayout(PainelPessoalLayout);
        PainelPessoalLayout.setHorizontalGroup(
            PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPessoalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPessoalLayout.createSequentialGroup()
                        .addComponent(Sexo)
                        .addGap(18, 18, 18)
                        .addComponent(UsuarioFeminino)
                        .addGap(18, 18, 18)
                        .addComponent(UsuarioMasculino))
                    .addGroup(PainelPessoalLayout.createSequentialGroup()
                        .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nome)
                            .addComponent(CPF))
                        .addGap(18, 18, 18)
                        .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CPFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelPessoalLayout.createSequentialGroup()
                        .addComponent(DataNasc)
                        .addGap(18, 18, 18)
                        .addComponent(DataNascUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(Nacionalidade)
                        .addGap(18, 18, 18)
                        .addComponent(NacionalidadeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelPessoalLayout.setVerticalGroup(
            PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPessoalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome)
                    .addComponent(NomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPF)
                    .addComponent(CPFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataNasc)
                    .addComponent(DataNascUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nacionalidade)
                    .addComponent(NacionalidadeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sexo)
                    .addComponent(UsuarioFeminino)
                    .addComponent(UsuarioMasculino))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        PainelEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações de Endereço"));

        Endereco.setText("Endereço:");

        Bairro.setText("Bairro:");

        Cidade.setText("Cidade:");

        UF.setText("UF:");

        UFUsuario.setToolTipText("Digite UF");

        CidadeUsuario.setToolTipText("Digite Cidade");

        BairroUsuario.setToolTipText("Digite Bairro");

        EnderecoUsuario.setToolTipText("Digite Endereço");

        Telefone.setText("Telefone:");

        TelUsuario.setToolTipText("Telefone");
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("(##)####-####");  
            TelUsuario = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }

        javax.swing.GroupLayout PainelEnderecoLayout = new javax.swing.GroupLayout(PainelEndereco);
        PainelEndereco.setLayout(PainelEnderecoLayout);
        PainelEnderecoLayout.setHorizontalGroup(
            PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelEnderecoLayout.createSequentialGroup()
                        .addComponent(Bairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BairroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(Cidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CidadeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(PainelEnderecoLayout.createSequentialGroup()
                        .addComponent(Endereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EnderecoUsuario)
                        .addContainerGap())
                    .addGroup(PainelEnderecoLayout.createSequentialGroup()
                        .addComponent(Telefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PainelEnderecoLayout.setVerticalGroup(
            PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Endereco)
                    .addComponent(EnderecoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bairro)
                    .addComponent(Cidade)
                    .addComponent(UF)
                    .addComponent(UFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CidadeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BairroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefone)
                    .addComponent(TelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        PainelTipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações de Tipo"));

        GrupoTipoUsuario.add(Dependente);
        Dependente.setText("Dependente");

        GrupoTipoUsuario.add(Titular);
        Titular.setText("Titular");

        TipodeUsuario.setText("Tipo de Usuário:");

        CPFdoDependente.setText("CPF Dependente:");

        CPFDependente.setToolTipText("CPF do Dependente");
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("###.###.###-##");  
            CPFDependente = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }

        Senha.setText("Senha:");

        SenhaUsuario.setToolTipText("Senha");

        javax.swing.GroupLayout PainelTipoLayout = new javax.swing.GroupLayout(PainelTipo);
        PainelTipo.setLayout(PainelTipoLayout);
        PainelTipoLayout.setHorizontalGroup(
            PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelTipoLayout.createSequentialGroup()
                        .addComponent(TipodeUsuario)
                        .addGap(18, 18, 18)
                        .addGroup(PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Titular)
                            .addComponent(Dependente)))
                    .addGroup(PainelTipoLayout.createSequentialGroup()
                        .addComponent(CPFdoDependente)
                        .addGap(18, 18, 18)
                        .addComponent(CPFDependente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelTipoLayout.createSequentialGroup()
                        .addComponent(Senha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelTipoLayout.setVerticalGroup(
            PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dependente)
                    .addComponent(TipodeUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Titular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPFdoDependente)
                    .addComponent(CPFDependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Senha)
                    .addComponent(SenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PainelCadastroUsuarioLayout = new javax.swing.GroupLayout(PainelCadastroUsuario);
        PainelCadastroUsuario.setLayout(PainelCadastroUsuarioLayout);
        PainelCadastroUsuarioLayout.setHorizontalGroup(
            PainelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PainelCadastroUsuarioLayout.createSequentialGroup()
                        .addComponent(PainelPessoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(PainelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PainelCadastroUsuarioLayout.setVerticalGroup(
            PainelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroUsuarioLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(PainelPessoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PainelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PainelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        BarraRolagemCadastroUsuario.setViewportView(PainelCadastroUsuario);

        getContentPane().add(BarraRolagemCadastroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 690, 260));

        MarcaPanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visaoTeste/panda_bg.png"))); // NOI18N
        getContentPane().add(MarcaPanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, -1));

        CancelarCadastroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testesgraficos/Fwdw_icons/grey/gif/24x24/001_05.gif"))); // NOI18N
        CancelarCadastroUsuario.setToolTipText("Cancelar Operação");
        CancelarCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarCadastroUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(CancelarCadastroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        LimparCadastroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testesgraficos/Fwdw_icons/grey/gif/24x24/001_39.gif"))); // NOI18N
        LimparCadastroUsuario.setToolTipText("Limpar Campos");
        LimparCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparCadastroUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(LimparCadastroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, -1));

        CadastrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testesgraficos/Fwdw_icons/grey/gif/24x24/001_06.gif"))); // NOI18N
        CadastrarUsuario.setToolTipText("Cadastrar Usuário");
        CadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(CadastrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        iCadastro.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        iCadastro.setText("iCadastro");
        getContentPane().add(iCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarCadastroUsuarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JanelaInicialiCards frame = new JanelaInicialiCards();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_CancelarCadastroUsuarioActionPerformed

    private void LimparCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparCadastroUsuarioActionPerformed
        // TODO add your handling code here:
        NomeUsuario.setText("");
        CPFUsuario.setText("");
        DataNascUsuario.setText("");
        SenhaUsuario.setText("");
        NacionalidadeUsuario.setText("");
        BairroUsuario.setText("");
        EnderecoUsuario.setText("");
        CidadeUsuario.setText("");
        UFUsuario.setText("");
        TelUsuario.setText("");
        UsuarioMasculino.setSelected(false);
        UsuarioFeminino.setSelected(false);
        Dependente.setSelected(false);
        Titular.setSelected(false);
       
    }//GEN-LAST:event_LimparCadastroUsuarioActionPerformed

    private void CadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarUsuarioActionPerformed
        // TODO add your handling code here:
        String nomeUsuario = NomeUsuario.getText();
        String cpfUsuario = CPFUsuario.getText();
        String dataNasc = DataNascUsuario.getText();
        String senhaUsuario = SenhaUsuario.getText();
        String nacionalidadeUsuario = NacionalidadeUsuario.getText();
        String bairroUsuario = BairroUsuario.getText();
        String enderecoUsuario = EnderecoUsuario.getText();
        String cidadeUsuario = CidadeUsuario.getText();
        String ufUsuario = UFUsuario.getText();
        String telUsuario = TelUsuario.getText();
        JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso!");
        this.dispose();
        JanelaInicialiCards frame = new JanelaInicialiCards();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        
    }//GEN-LAST:event_CadastrarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCadastrarUsuario().setVisible(true);
            }
              
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bairro;
    private javax.swing.JTextField BairroUsuario;
    private javax.swing.JScrollPane BarraRolagemCadastroUsuario;
    private javax.swing.JLabel CPF;
    private javax.swing.JFormattedTextField CPFDependente;
    private javax.swing.JFormattedTextField CPFUsuario;
    private javax.swing.JLabel CPFdoDependente;
    private javax.swing.JButton CadastrarUsuario;
    private javax.swing.JButton CancelarCadastroUsuario;
    private javax.swing.JLabel Cidade;
    private javax.swing.JTextField CidadeUsuario;
    private javax.swing.JLabel DataNasc;
    private javax.swing.JFormattedTextField DataNascUsuario;
    private javax.swing.JRadioButton Dependente;
    private javax.swing.JLabel Endereco;
    private javax.swing.JTextField EnderecoUsuario;
    private javax.swing.ButtonGroup GrupoSexo;
    private javax.swing.ButtonGroup GrupoTipoUsuario;
    private javax.swing.JButton LimparCadastroUsuario;
    private javax.swing.JLabel MarcaPanda;
    private javax.swing.JLabel Nacionalidade;
    private javax.swing.JTextField NacionalidadeUsuario;
    private javax.swing.JLabel Nome;
    private javax.swing.JTextField NomeUsuario;
    private javax.swing.JPanel PainelCadastroUsuario;
    private javax.swing.JPanel PainelEndereco;
    private javax.swing.JPanel PainelPessoal;
    private javax.swing.JPanel PainelTipo;
    private javax.swing.JLabel Senha;
    private javax.swing.JPasswordField SenhaUsuario;
    private javax.swing.JLabel Sexo;
    private javax.swing.JFormattedTextField TelUsuario;
    private javax.swing.JLabel Telefone;
    private javax.swing.JLabel TipodeUsuario;
    private javax.swing.JRadioButton Titular;
    private javax.swing.JLabel UF;
    private javax.swing.JTextField UFUsuario;
    private javax.swing.JRadioButton UsuarioFeminino;
    private javax.swing.JRadioButton UsuarioMasculino;
    private javax.swing.JLabel iCadastro;
    // End of variables declaration//GEN-END:variables
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("favicon.png")));
    }
}
