/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Leandro
 */
public class JanelaEditarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form JanelaGerenciarUsuario
     */
    public JanelaEditarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tipo = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        PainelCadastroUsuario = new javax.swing.JPanel();
        PainelPessoal = new javax.swing.JPanel();
        CPF = new javax.swing.JLabel();
        DataNasc = new javax.swing.JLabel();
        Sexo = new javax.swing.JLabel();
        NomeUsuario = new javax.swing.JTextField();
        Nome = new javax.swing.JLabel();
        DataNascUsuario = new javax.swing.JFormattedTextField();
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/####");  
            DataNascUsuario = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }
        Nacionalidade = new javax.swing.JLabel();
        NacionalidadeUsuario = new javax.swing.JTextField();
        UsuarioFeminino = new javax.swing.JRadioButton();
        UsuarioMasculino = new javax.swing.JRadioButton();
        CPFUsuario = new javax.swing.JFormattedTextField();
        PainelEndereco = new javax.swing.JPanel();
        Endereco = new javax.swing.JLabel();
        Bairro = new javax.swing.JLabel();
        Cidade = new javax.swing.JLabel();
        UF = new javax.swing.JLabel();
        UFUsuario = new javax.swing.JTextField();
        CidadeUsuario = new javax.swing.JTextField();
        BairroUsuario = new javax.swing.JTextField();
        EnderecoUsuario = new javax.swing.JTextField();
        Telefone = new javax.swing.JLabel();
        TelUsuario = new javax.swing.JFormattedTextField();
        PainelTipo = new javax.swing.JPanel();
        Dependente = new javax.swing.JRadioButton();
        Titular = new javax.swing.JRadioButton();
        TipodeUsuario = new javax.swing.JLabel();
        CPFdoDependente = new javax.swing.JLabel();
        CPFDependente = new javax.swing.JFormattedTextField();
        Senha = new javax.swing.JLabel();
        SenhaUsuario = new javax.swing.JPasswordField();
        ConfirmarEdicaoUsuario = new javax.swing.JButton();
        LimparEdicaoUsuario = new javax.swing.JButton();
        CancelarEdicaoUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelPessoal.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações Pessoais"));

        CPF.setText("CPF:");

        DataNasc.setText("Data de Nascimento:");

        Sexo.setText("Sexo:");

        NomeUsuario.setToolTipText("Nome");

        Nome.setText("Nome:");

        DataNascUsuario.setToolTipText("Data de Nascimento");

        Nacionalidade.setText("Nacionalidade:");

        NacionalidadeUsuario.setToolTipText("Nacionalidade");

        UsuarioFeminino.setText("Feminino");
        UsuarioFeminino.setToolTipText("Selecione Feminino");

        UsuarioMasculino.setText("Masculino");
        UsuarioMasculino.setToolTipText("Selecione Masculino");

        CPFUsuario.setEditable(false);
        CPFUsuario.setToolTipText("CPF do Usuário");
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("###.###.###-##");  
            CPFUsuario = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }

        javax.swing.GroupLayout PainelPessoalLayout = new javax.swing.GroupLayout(PainelPessoal);
        PainelPessoal.setLayout(PainelPessoalLayout);
        PainelPessoalLayout.setHorizontalGroup(
            PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPessoalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPessoalLayout.createSequentialGroup()
                        .addComponent(Sexo)
                        .addGap(18, 18, 18)
                        .addComponent(UsuarioFeminino)
                        .addGap(18, 18, 18)
                        .addComponent(UsuarioMasculino))
                    .addGroup(PainelPessoalLayout.createSequentialGroup()
                        .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nome)
                            .addComponent(CPF))
                        .addGap(18, 18, 18)
                        .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CPFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelPessoalLayout.createSequentialGroup()
                        .addComponent(DataNasc)
                        .addGap(18, 18, 18)
                        .addComponent(DataNascUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(Nacionalidade)
                        .addGap(18, 18, 18)
                        .addComponent(NacionalidadeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        PainelPessoalLayout.setVerticalGroup(
            PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPessoalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome)
                    .addComponent(NomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPF)
                    .addComponent(CPFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataNasc)
                    .addComponent(DataNascUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nacionalidade)
                    .addComponent(NacionalidadeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sexo)
                    .addComponent(UsuarioFeminino)
                    .addComponent(UsuarioMasculino))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações de Endereço"));

        Endereco.setText("Endereço:");

        Bairro.setText("Bairro:");

        Cidade.setText("Cidade:");

        UF.setText("UF:");

        UFUsuario.setToolTipText("Digite UF");

        CidadeUsuario.setToolTipText("Digite Cidade");

        BairroUsuario.setToolTipText("Digite Bairro");

        EnderecoUsuario.setToolTipText("Digite Endereço");

        Telefone.setText("Telefone:");

        TelUsuario.setToolTipText("Telefone");
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("(##)####-####");  
            TelUsuario = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }

        javax.swing.GroupLayout PainelEnderecoLayout = new javax.swing.GroupLayout(PainelEndereco);
        PainelEndereco.setLayout(PainelEnderecoLayout);
        PainelEnderecoLayout.setHorizontalGroup(
            PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelEnderecoLayout.createSequentialGroup()
                        .addComponent(Telefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PainelEnderecoLayout.createSequentialGroup()
                        .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Endereco)
                            .addComponent(Bairro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelEnderecoLayout.createSequentialGroup()
                                .addComponent(BairroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(Cidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CidadeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(EnderecoUsuario))
                        .addContainerGap())))
        );
        PainelEnderecoLayout.setVerticalGroup(
            PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Endereco)
                    .addComponent(EnderecoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bairro)
                    .addComponent(Cidade)
                    .addComponent(UF)
                    .addComponent(UFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CidadeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BairroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefone)
                    .addComponent(TelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        PainelTipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações de Tipo"));
        PainelTipo.setPreferredSize(new java.awt.Dimension(680, 150));

        Tipo.add(Dependente);
        Dependente.setText("Dependente");
        Dependente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DependenteActionPerformed(evt);
            }
        });

        Tipo.add(Titular);
        Titular.setText("Titular");
        Titular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitularActionPerformed(evt);
            }
        });

        TipodeUsuario.setText("Tipo de Usuário:");

        CPFdoDependente.setText("CPF Dependente:");

        CPFDependente.setEditable(false);
        CPFDependente.setToolTipText("CPF do Dependente");
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("###.###.###-##");  
            CPFDependente = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }
        CPFDependente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPFDependenteActionPerformed(evt);
            }
        });

        Senha.setText("Senha:");

        SenhaUsuario.setToolTipText("Senha");

        javax.swing.GroupLayout PainelTipoLayout = new javax.swing.GroupLayout(PainelTipo);
        PainelTipo.setLayout(PainelTipoLayout);
        PainelTipoLayout.setHorizontalGroup(
            PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelTipoLayout.createSequentialGroup()
                        .addComponent(TipodeUsuario)
                        .addGap(18, 18, 18)
                        .addGroup(PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Titular)
                            .addComponent(Dependente)))
                    .addGroup(PainelTipoLayout.createSequentialGroup()
                        .addComponent(CPFdoDependente)
                        .addGap(18, 18, 18)
                        .addComponent(CPFDependente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelTipoLayout.createSequentialGroup()
                        .addComponent(Senha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelTipoLayout.setVerticalGroup(
            PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dependente)
                    .addComponent(TipodeUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Titular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPFdoDependente)
                    .addComponent(CPFDependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Senha)
                    .addComponent(SenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PainelCadastroUsuarioLayout = new javax.swing.GroupLayout(PainelCadastroUsuario);
        PainelCadastroUsuario.setLayout(PainelCadastroUsuarioLayout);
        PainelCadastroUsuarioLayout.setHorizontalGroup(
            PainelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelPessoal, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PainelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                    .addComponent(PainelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE))
                .addContainerGap())
        );
        PainelCadastroUsuarioLayout.setVerticalGroup(
            PainelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelPessoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PainelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(PainelCadastroUsuario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 420));

        ConfirmarEdicaoUsuario.setText("Confirmar");
        ConfirmarEdicaoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarEdicaoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmarEdicaoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 100, 30));

        LimparEdicaoUsuario.setText("Limpar");
        LimparEdicaoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparEdicaoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(LimparEdicaoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 100, 30));

        CancelarEdicaoUsuario.setText("Cancelar");
        CancelarEdicaoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarEdicaoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(CancelarEdicaoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 100, 30));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-728)/2, (screenSize.height-514)/2, 728, 514);
    }// </editor-fold>//GEN-END:initComponents

    private void LimparEdicaoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparEdicaoUsuarioActionPerformed
        // TODO add your handling code here:
        NomeUsuario.setText("");
        CPFUsuario.setText("");
        DataNascUsuario.setText("");
        SenhaUsuario.setText("");
        NacionalidadeUsuario.setText("");
        BairroUsuario.setText("");
        EnderecoUsuario.setText("");
        CidadeUsuario.setText("");
        UFUsuario.setText("");
        TelUsuario.setText("");
        UsuarioMasculino.setSelected(false);
        UsuarioFeminino.setSelected(false);
        Dependente.setSelected(false);
        Titular.setSelected(false);
    }//GEN-LAST:event_LimparEdicaoUsuarioActionPerformed

    private void ConfirmarEdicaoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarEdicaoUsuarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ConfirmarEdicaoUsuarioActionPerformed

    private void CancelarEdicaoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarEdicaoUsuarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JanelaInicioAdmin frame = new JanelaInicioAdmin();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_CancelarEdicaoUsuarioActionPerformed

    private void CPFDependenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPFDependenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPFDependenteActionPerformed

    private void TitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitularActionPerformed
        // TODO add your handling code here:
        CPFDependente.setEnabled(false);
        CPFdoDependente.setForeground(new java.awt.Color(155, 155, 155));
    }//GEN-LAST:event_TitularActionPerformed

    private void DependenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DependenteActionPerformed
        // TODO add your handling code here:
        CPFDependente.setEnabled(true);
        CPFdoDependente.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_DependenteActionPerformed
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaEditarUsuario().setVisible(true);
                    
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bairro;
    private javax.swing.JTextField BairroUsuario;
    private javax.swing.JLabel CPF;
    private javax.swing.JFormattedTextField CPFDependente;
    private javax.swing.JFormattedTextField CPFUsuario;
    private javax.swing.JLabel CPFdoDependente;
    private javax.swing.JButton CancelarEdicaoUsuario;
    private javax.swing.JLabel Cidade;
    private javax.swing.JTextField CidadeUsuario;
    private javax.swing.JButton ConfirmarEdicaoUsuario;
    private javax.swing.JLabel DataNasc;
    private javax.swing.JFormattedTextField DataNascUsuario;
    private javax.swing.JRadioButton Dependente;
    private javax.swing.JLabel Endereco;
    private javax.swing.JTextField EnderecoUsuario;
    private javax.swing.JButton LimparEdicaoUsuario;
    private javax.swing.JLabel Nacionalidade;
    private javax.swing.JTextField NacionalidadeUsuario;
    private javax.swing.JLabel Nome;
    private javax.swing.JTextField NomeUsuario;
    private javax.swing.JPanel PainelCadastroUsuario;
    private javax.swing.JPanel PainelEndereco;
    private javax.swing.JPanel PainelPessoal;
    private javax.swing.JPanel PainelTipo;
    private javax.swing.JLabel Senha;
    private javax.swing.JPasswordField SenhaUsuario;
    private javax.swing.JLabel Sexo;
    private javax.swing.JFormattedTextField TelUsuario;
    private javax.swing.JLabel Telefone;
    private javax.swing.ButtonGroup Tipo;
    private javax.swing.JLabel TipodeUsuario;
    private javax.swing.JRadioButton Titular;
    private javax.swing.JLabel UF;
    private javax.swing.JTextField UFUsuario;
    private javax.swing.JRadioButton UsuarioFeminino;
    private javax.swing.JRadioButton UsuarioMasculino;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
